name_length: 50
email_length: 255
password_min_length: 6
checker: "1"
avatar_size: 80
avatar_small: 50
checked: "1"
default_from_email: "noreply@example.com"
address: "smtp.gmail.com"
port: 587
domain: "gmail.com"
authentication: "plain"
enable_auto: true
protocol: "http"
password_expire_time: 2
